# Generated by Django 5.2 on 2026-06-26 00:17

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('body', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('source_type', models.CharField(choices=[('naver_news', '네이버 뉴스'), ('opendart', 'OpenDART'), ('rss', 'RSS')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('기술흐름', '기술 흐름'), ('기업사례', '기업 사례'), ('금융권활용', '금융권 활용'), ('규제·정책', '규제·정책'), ('경쟁사동향', '경쟁사 동향')], max_length=20)),
                ('tags', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('implication', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='news.issuegroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueGroupNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.issuegroup')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'unique_together': {('issue_group', 'news')},
            },
        ),
        migrations.AddField(
            model_name='issuegroup',
            name='news',
            field=models.ManyToManyField(related_name='issue_groups', through='news.IssueGroupNews', to='news.news'),
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='news.news')),
            ],
        ),
    ]
