# Generated by Django 5.2 on 2026-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('setting', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='news', to='setting.organization'),
        ),
    ]
