# Generated by Django 5.2 on 2026-07-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_embedding_voyage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
