# Generated by Django 5.2 on 2026-07-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_excludedurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-pk']},
        ),
    ]
