# Generated by Django 5.2 on 2026-07-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_type',
            field=models.CharField(max_length=20),
        ),
    ]
