# Generated by Django 5.2 on 2026-07-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
