# Generated by Django 5.2 on 2026-07-09 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_is_relevant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='issue_group',
        ),
        migrations.AlterUniqueTogether(
            name='issuegroupnews',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_relevant',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
        migrations.AddField(
            model_name='insight',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InsightNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.insight')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'unique_together': {('insight', 'news')},
            },
        ),
        migrations.AddField(
            model_name='insight',
            name='news',
            field=models.ManyToManyField(related_name='insights', through='news.InsightNews', to='news.news'),
        ),
        migrations.DeleteModel(
            name='IssueGroup',
        ),
        migrations.DeleteModel(
            name='IssueGroupNews',
        ),
    ]
