# Generated by Django 5.2 on 2026-07-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_insight_issue_group_and_more'),
        ('setting', '0009_techtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tech_topics',
            field=models.ManyToManyField(blank=True, related_name='news', to='setting.techtopic'),
        ),
    ]
