# Generated by Django 5.2 on 2026-08-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_tech_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('미검증', '미검증'), ('검증됨', '검증됨')], db_index=True, default='미검증', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
