# Generated by Django 5.2 on 2026-08-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_verify_existing_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedNewsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('body', models.TextField(blank=True, help_text='수집 시점 크롤링본 그대로. 요약·가공하지 않는다. 외부 공개·재발행 금지(내부 판별 로직 개발 재료 용도로 한정).')),
                ('source_type', models.CharField(max_length=20)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField()),
                ('criterion_code', models.CharField(blank=True, help_text="권장 어휘(고정 choices 아님 — docs/planning.md '판정 기록 보존 정책' 1번 근거: 관련성 판단 기준이 계속 개정되므로 enum으로 박지 않는다): 1-a(배경 언급) / 1-b(부차 요소) / 2(중복 보도) / 3(키워드 오탐) / 4(증시 브리핑) / 5(AI 단독, 금융 연결 없음) / S-KLS(임시 스코프 제외) / 기타", max_length=20)),
                ('reason', models.TextField(blank=True, help_text='삭제 사유 1~2문장 자유 서술')),
                ('judged_by', models.CharField(default='RA', help_text='권장 어휘: RA / 사용자(화면 삭제) / 소급 정비 / 자동 판정', max_length=30)),
                ('organizations_snapshot', models.JSONField(blank=True, default=list, help_text='삭제 시점 연결돼 있던 Organization.name 목록')),
                ('tech_topics_snapshot', models.JSONField(blank=True, default=list, help_text='삭제 시점 연결돼 있던 TechTopic.name 목록')),
                ('judged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-judged_at'],
            },
        ),
    ]
