# Generated by Django 5.2 on 2026-08-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_deletednewsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCorrectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('organization', '기업'), ('tech_topic', '기술 주제')], max_length=20)),
                ('action', models.CharField(choices=[('add', '추가'), ('remove', '제거')], max_length=10)),
                ('target_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, help_text='교정 사유, 짧게(1문장 권장)')),
                ('judged_by', models.CharField(default='RA', help_text='권장 어휘: RA / 사용자(화면 삭제) / 소급 정비 / 자동 판정', max_length=30)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_corrections', to='news.news')),
            ],
            options={
                'ordering': ['-corrected_at'],
            },
        ),
    ]
