# Generated by Django 5.2 on 2026-08-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_tagcorrectionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletednewsrecord',
            name='matched_keywords_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='삭제 시점 News.matched_keywords 그대로. 2026-08-06 이전 삭제 이력은 이 필드 도입 전이라 빈 리스트(소급 채움 없음).'),
        ),
        migrations.AddField(
            model_name='news',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list, help_text='수집 시 매칭된 Keyword.keyword 문자열 목록. 2026-08-06 이전 수집분은 이 필드 도입 전이라 빈 리스트(소급 채움 없음).'),
        ),
    ]
