# Generated by Django 5.2 on 2026-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_deletednewsrecord_matched_keywords_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='grade',
            field=models.CharField(choices=[('unspecified', '미지정'), ('1', '1급'), ('2', '2급'), ('3', '3급')], db_index=True, default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='insight',
            name='headliner_order',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
