# Generated by Django 5.2 on 2026-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_insight_grade_insight_headliner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='content_short',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='implication_short',
            field=models.TextField(blank=True),
        ),
    ]
