# Generated by Django 5.2 on 2026-09-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_insight_content_short_insight_implication_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='insight_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
