# Generated by Django 5.2 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_insight_dismissed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletednewsrecord',
            name='judged_by',
            field=models.CharField(default='RA', help_text='권장 어휘: RA / 사용자(화면 삭제) / 소급 정비 / 자동 판정 / 코드(AI 낱말 규칙)', max_length=30),
        ),
    ]
