# Generated by Django 5.2 on 2026-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_deletednewsrecord_judged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletednewsrecord',
            name='criterion_code',
            field=models.CharField(blank=True, help_text="권장 어휘(고정 choices 아님 — docs/planning.md '판정 기록 보존 정책' 1번 근거: 관련성 판단 기준이 계속 개정되므로 enum으로 박지 않는다): 1-a(배경 언급) / 1-b(부차 요소) / 2(중복 보도) / 3(키워드 오탐) / 4(증시 브리핑) / 5(AI 단독, 금융 연결 없음) / 6(묶음, 단신 브리핑 기사) / S-KLS(임시 스코프 제외) / 기타", max_length=20),
        ),
    ]
