# Generated by Django 5.2 on 2026-09-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_deletednewsrecord_criterion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='classify_fail_count',
            field=models.IntegerField(default=0),
        ),
    ]
