# Generated by Django 5.2 on 2026-09-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_news_classify_fail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='같은 사건을 다루는 대표 News. 대표 기사 자신은 None이다. status는 두 기사 모두 그대로 둔다 — 이 필드로만 묶고 삭제하지 않는다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='news.news'),
        ),
    ]
