# Generated by Django 5.2 on 2026-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_news_duplicate_of'),
        ('setting', '0031_runjob_relation_target_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(condition=models.Q(('headliner_order__isnull', False)), fields=['headliner_order'], name='insight_headliner_order_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published_at'], name='news_published_at_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'duplicate_of'], name='news_status_dup_idx'),
        ),
    ]
