from django.urls import path
from . import views

urlpatterns = [
    path("run/", views.setting_run, name="setting_run"),
    path("run/graph/", views.setting_run_graph, name="setting_run_graph"),
    path("run/<str:job>/start/", views.setting_run_start, name="setting_run_start"),
    path("run/review/<str:job>/", views.setting_run_review, name="setting_run_review"),
    path("run/review/<str:job>/confirm/", views.setting_run_review_confirm, name="setting_run_review_confirm"),
    path("run/review/<str:job>/cancel/", views.setting_run_review_cancel, name="setting_run_review_cancel"),
    path("sources/", views.sources, name="setting_sources"),
    path("sources/<int:pk>/toggle/", views.source_toggle, name="setting_source_toggle"),
    path("sources/collect-now/", views.collect_now, name="setting_collect_now"),
    path("keywords/", views.keywords, name="setting_keywords"),
    path("keywords/add/", views.keyword_add, name="setting_keyword_add"),
    path("keywords/<int:pk>/update/", views.keyword_update, name="setting_keyword_update"),
    path("keywords/<int:pk>/delete/", views.keyword_delete, name="setting_keyword_delete"),
    path("slack/", views.slack, name="setting_slack"),
    path("logs/", views.logs, name="setting_logs"),
    path("organizations/", views.organizations, name="setting_organizations"),
    path("organizations/save/", views.organization_save, name="setting_organization_save"),
    path("organizations/<int:pk>/toggle/", views.organization_toggle, name="setting_organization_toggle"),
    path("organizations/<int:pk>/delete/", views.organization_delete, name="setting_organization_delete"),
    path("remap/", views.remap_now, name="setting_remap_now"),
    path("tech-topics/", views.tech_topics, name="setting_tech_topics"),
    path("tech-topics/save/", views.tech_topic_save, name="setting_tech_topic_save"),
    path("tech-topics/<int:pk>/toggle/", views.tech_topic_toggle, name="setting_tech_topic_toggle"),
    path("tech-topics/<int:pk>/delete/", views.tech_topic_delete, name="setting_tech_topic_delete"),
    path("tech-topics/remap/", views.remap_tech_topics_now, name="setting_remap_tech_topics_now"),
    path("newsroom/", views.setting_newsroom, name="setting_newsroom"),
    path("newsroom/save/", views.setting_newsroom_save, name="setting_newsroom_save"),
    path("newsroom/<int:pk>/delete/", views.setting_newsroom_delete, name="setting_newsroom_delete"),
    path("newsroom/<int:pk>/collect/", views.setting_newsroom_collect, name="setting_newsroom_collect"),
    path("newsroom/<int:room_pk>/keywords/add/", views.setting_newsroom_keyword_add, name="setting_newsroom_keyword_add"),
    path("newsroom/<int:room_pk>/keywords/<int:pk>/update/", views.setting_newsroom_keyword_update, name="setting_newsroom_keyword_update"),
    path("newsroom/<int:room_pk>/keywords/<int:pk>/delete/", views.setting_newsroom_keyword_delete, name="setting_newsroom_keyword_delete"),
]
