# Generated by Django 5.2 on 2026-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('org_type', models.CharField(choices=[('금융사', '금융사'), ('보험사', '보험사'), ('IT', 'IT'), ('AI', 'AI')], max_length=20)),
                ('aliases', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['org_type', 'name'],
            },
        ),
    ]
