# Generated by Django 5.2 on 2026-06-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_merge_it_into_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_type',
            field=models.CharField(choices=[('수집', '수집'), ('제외', '제외'), ('컨텍스트', '컨텍스트')], default='수집', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('금융사', '금융사'), ('보험사', '보험사'), ('AI', 'AI')], max_length=20),
        ),
    ]
