# Generated by Django 5.2 on 2026-07-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_remove_news_summary_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('aliases', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
