# Generated by Django 5.2 on 2026-07-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_tech_topics'),
        ('setting', '0010_seed_techtopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ManyToManyField(blank=True, related_name='org_relations', to='news.news')),
                ('org_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_a', to='setting.organization')),
                ('org_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_b', to='setting.organization')),
            ],
            options={
                'unique_together': {('org_a', 'org_b')},
            },
        ),
    ]
