# Generated by Django 5.2 on 2026-08-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_orgrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlog',
            name='actor',
            field=models.CharField(choices=[('자동(스케줄)', '자동(스케줄)'), ('수동(화면)', '수동(화면)'), ('자동 복구(catch-up)', '자동 복구(catch-up)')], default='자동(스케줄)', max_length=20),
        ),
    ]
