# Generated by Django 5.2 on 2026-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_collectionlog_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionlog',
            name='crawl_failed_count',
            field=models.IntegerField(default=0),
        ),
    ]
