# Generated by Django 5.2 on 2026-09-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_collectionlog_crawl_failed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlog',
            name='actor',
            field=models.CharField(choices=[('자동(스케줄)', '자동(스케줄)'), ('수동(화면)', '수동(화면)'), ('자동 복구(catch-up)', '자동 복구(catch-up)')], default='수동(화면)', max_length=20),
        ),
    ]
