# Generated by Django 5.2 on 2026-09-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_insight_content_short_insight_implication_short'),
        ('setting', '0014_alter_collectionlog_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_key', models.CharField(db_index=True, help_text="apps/setting/views.py RUN_JOB_KEYS의 값(collect, cleanup 등). 그 목록이 계속 늘 수 있어 고정 choices로 박지 않는다 — DeletedNewsRecord.criterion_code와 같은 이유(docs/planning.md '판정 기록 보존 정책' 1번).", max_length=30)),
                ('status', models.CharField(choices=[('대기', '대기'), ('진행중', '진행중'), ('완료', '완료'), ('실패', '실패'), ('중단됨', '중단됨'), ('확정됨', '확정됨'), ('취소됨', '취소됨')], default='대기', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('target_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('actor', models.CharField(choices=[('화면', '화면'), ('관리 명령', '관리 명령')], default='화면', max_length=20)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', '진행중')), fields=('status',), name='unique_running_run_job')],
            },
        ),
        migrations.CreateModel(
            name='RunProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('삭제', '삭제'), ('유지', '유지'), ('태그 제거', '태그 제거'), ('태그 추가', '태그 추가')], max_length=10)),
                ('criterion_code', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('target_name', models.CharField(blank=True, help_text='태그 제거/추가 제안의 대상 Organization/TechTopic 이름. 삭제/유지 제안은 비워 둔다. FK가 아니라 문자열인 이유는 클래스 docstring 참고.', max_length=200)),
                ('axis', models.CharField(blank=True, choices=[('organization', '기업'), ('tech_topic', '기술 주제')], help_text='태그 제거/추가 제안의 축(기업/기술 주제). 삭제/유지 제안은 비워 둔다. FK가 아니라 문자열인 이유는 클래스 docstring 참고.', max_length=20)),
                ('status', models.CharField(choices=[('대기', '대기'), ('채택', '채택'), ('거절', '거절'), ('취소', '취소')], default='대기', max_length=10)),
                ('judged_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_proposals', to='news.news')),
                ('run_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='setting.runjob')),
            ],
            options={
                'ordering': ['-judged_at', '-pk'],
            },
        ),
    ]
