# Generated by Django 5.2 on 2026-09-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_runjob_runproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runproposal',
            name='proposal_type',
            field=models.CharField(choices=[('삭제', '삭제'), ('유지', '유지'), ('태그 제거', '태그 제거'), ('태그 추가', '태그 추가'), ('기업 후보', '기업 후보')], max_length=10),
        ),
    ]
