# Generated by Django 5.2 on 2026-09-15 03:47

from django.db import migrations, models


def forwards_generalize_org_candidate(apps, schema_editor):
    """`기업 후보`(TYPE_ORG_CANDIDATE)를 `태그 후보`(TYPE_TAG_CANDIDATE)로 일반화한다
    (docs/planning.md 4-(b) 🔴 개정 (2026-09-15)). 이 라운드 이전에는 후보 종류가
    기업 전용이었으므로, 기존 행은 전부 축이 기업이었다는 것이 스키마상 사실이다 —
    axis="organization"으로 채우는 것은 데이터를 새로 판단하는 것이 아니라 그동안
    필드가 없어 비워 뒀던 값을 되짚어 채우는 것이다."""
    RunProposal = apps.get_model('setting', 'RunProposal')
    RunProposal.objects.filter(proposal_type='기업 후보').update(
        proposal_type='태그 후보', axis='organization',
    )


def backwards_generalize_org_candidate(apps, schema_editor):
    """역방향 — `axis="organization"`인 `태그 후보` 행을 `기업 후보`로 되돌린다. 이
    라운드 이후에 실제로 기술 주제 축 후보가 쌓였다면(정상 경로) 그 행들은 축 정보를
    잃고 `기업 후보`로 잘못 되돌아간다 — 이 마이그레이션을 되돌리는 것은 시간을
    거슬러 스키마 공백을 다시 만드는 것이므로 원래 손실을 동반한다. 롤백은 개발
    환경에서만, 이 라운드를 아예 되돌릴 때만 쓴다."""
    RunProposal = apps.get_model('setting', 'RunProposal')
    RunProposal.objects.filter(proposal_type='태그 후보', axis='organization').update(
        proposal_type='기업 후보', axis='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_alter_runproposal_proposal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='cache_creation_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runjob',
            name='cache_read_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runjob',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runjob',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runproposal',
            name='axis',
            field=models.CharField(blank=True, choices=[('organization', '기업'), ('tech_topic', '기술 주제')], help_text='태그 제거/추가/후보 제안의 축(기업/기술 주제). 삭제/유지 제안은 비워 둔다. FK가 아니라 문자열인 이유는 클래스 docstring 참고.', max_length=20),
        ),
        migrations.AlterField(
            model_name='runproposal',
            name='proposal_type',
            field=models.CharField(choices=[('삭제', '삭제'), ('유지', '유지'), ('태그 제거', '태그 제거'), ('태그 추가', '태그 추가'), ('태그 후보', '태그 후보')], max_length=10),
        ),
        migrations.RunPython(
            forwards_generalize_org_candidate, backwards_generalize_org_candidate,
        ),
    ]
