# Generated by Django 5.2 on 2026-09-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_insight_content_short_insight_implication_short'),
        ('reports', '0005_report_note'),
        ('setting', '0017_tag_candidate_and_usage_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('이슈', '이슈'), ('주간 보고서', '주간 보고서'), ('월간 보고서', '월간 보고서')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Insight.content 또는 Report.content.')),
                ('implication', models.TextField(blank=True, help_text='이슈 전용. Insight.implication.')),
                ('overview', models.TextField(blank=True, help_text='보고서 전용. Report.overview.')),
                ('grade', models.CharField(blank=True, choices=[('unspecified', '미지정'), ('1', '1급'), ('2', '2급'), ('3', '3급')], default='', help_text='이슈 전용. Insight.GRADE_CHOICES를 그대로 참조한다.', max_length=20)),
                ('date_from', models.DateField(blank=True, help_text='보고서 전용.', null=True)),
                ('date_to', models.DateField(blank=True, help_text='보고서 전용.', null=True)),
                ('status', models.CharField(choices=[('대기', '대기'), ('채택', '채택'), ('거절', '거절'), ('취소', '취소')], default='대기', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_drafts', to='news.insight')),
                ('created_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_drafts', to='reports.report')),
                ('news', models.ManyToManyField(help_text='근거 기사.', related_name='run_drafts', to='news.news')),
                ('run_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='setting.runjob')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
