# Generated by Django 5.2 on 2026-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0018_rundraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundraft',
            name='grade_reason',
            field=models.TextField(blank=True, help_text='이슈 전용. LLM이 그 등급을 고른 이유.'),
        ),
    ]
