# Generated by Django 5.2 on 2026-09-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_rundraft_grade_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='runproposal',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text="이 제안(채택된 '유지')이 확정 뒤에 뒤집혀 삭제된 시각. delete_news_with_record()가 자동으로 채운다. judged_at은 제안이 만들어진 시각이라 이 값에 쓸 수 없다(auto_now_add).", null=True),
        ),
        migrations.AddField(
            model_name='runproposal',
            name='reversed_by',
            field=models.CharField(blank=True, help_text='뒤집은 주체. DeletedNewsRecord 판정 주체 어휘를 그대로 쓴다(RA / 사용자(화면 삭제) / 소급 정비 / 자동 판정) — delete_news_with_record() 호출 시 넘긴 judged_by 값이 그대로 들어온다.', max_length=30),
        ),
    ]
