# Generated by Django 5.2 on 2026-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0020_runproposal_reversed_at_runproposal_reversed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='title_rejected_count',
            field=models.IntegerField(default=0),
        ),
    ]
