# Generated by Django 5.2 on 2026-09-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_insight_dismissed_at'),
        ('setting', '0021_runjob_title_rejected_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runjob',
            name='insight_candidates',
            field=models.ManyToManyField(blank=True, related_name='+', to='news.news'),
        ),
    ]
