# Generated by Django 5.2 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0022_runjob_confirmed_at_runjob_insight_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='runproposal',
            name='judged_by',
            field=models.CharField(blank=True, default='', help_text="빈 값=LLM 판정. 코드 사전 차단 제안만 '코드(AI 낱말 규칙)'를 채운다.", max_length=30),
        ),
    ]
