# Generated by Django 5.2 on 2026-09-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0023_runproposal_judged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='regression_flag_count',
            field=models.IntegerField(default=0),
        ),
    ]
