# Generated by Django 5.2 on 2026-09-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0024_runjob_regression_flag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='stop_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
