# Generated by Django 5.2 on 2026-09-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0025_runjob_stop_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='runproposal',
            name='reject_code',
            field=models.CharField(blank=True, default='', help_text="거절(status='거절')을 받을 사람. '오적용'(PE) / '기준재검토'(PM) / '기타'(자유 서술 필수) / '미기입'(안 고름). 자유 문자열이다. 삭제 제안에만 채운다 — 태그 교정 행은 항상 빈 값이다.", max_length=20),
        ),
        migrations.AddField(
            model_name='runproposal',
            name='reject_note',
            field=models.TextField(blank=True, default='', help_text="reject_code가 '기타'일 때만 채우는 자유 서술."),
        ),
    ]
