# Generated by Django 5.2 on 2026-09-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_news_duplicate_of'),
        ('setting', '0026_runproposal_reject_code_runproposal_reject_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='runproposal',
            name='dup_fingerprint',
            field=models.JSONField(blank=True, default=list, help_text="TYPE_DUPLICATE 제안이 속한 묶음의 공통 표현 토큰 목록(예: ['ADAS', '이미지 판독']). 같은 묶음의 행은 같은 값을 중복해 담는다. 그 외 제안은 빈 리스트다."),
        ),
        migrations.AddField(
            model_name='runproposal',
            name='dup_pick_reason',
            field=models.CharField(blank=True, choices=[('existing', '기존분'), ('longest', '본문 최장'), ('linked', '근거 있음')], default='', help_text='duplicate_representative를 고른 이유. TYPE_DUPLICATE 제안에만 채운다.', max_length=20),
        ),
        migrations.AddField(
            model_name='runproposal',
            name='duplicate_representative',
            field=models.ForeignKey(blank=True, help_text='TYPE_DUPLICATE 제안이 속한 묶음의 대표 News. 확정하면 대상 News.duplicate_of에 이 값이 들어간다(삭제하지 않는다). 삭제/유지/태그 제안은 비워 둔다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.news'),
        ),
        migrations.AlterField(
            model_name='runproposal',
            name='proposal_type',
            field=models.CharField(choices=[('삭제', '삭제'), ('유지', '유지'), ('태그 제거', '태그 제거'), ('태그 추가', '태그 추가'), ('태그 후보', '태그 후보'), ('중복 보도', '중복 보도')], max_length=10),
        ),
        migrations.AlterField(
            model_name='runproposal',
            name='reject_code',
            field=models.CharField(blank=True, default='', help_text="거절(status='거절')을 받을 사람. '오적용'(PE) / '기준재검토'(PM) / '기타'(자유 서술 필수) / '미기입'(안 고름). 자유 문자열이다. 삭제/중복 보도 제안에만 채운다 — 태그 교정 행은 항상 빈 값이다.", max_length=20),
        ),
    ]
