# Generated by Django 5.2 on 2026-09-17 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0027_runproposal_dup_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundraft',
            name='created_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_drafts', to='setting.orgrelation'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='relation_label',
            field=models.CharField(blank=True, default='', help_text='관계 전용. 7종 어휘(기술협업/공동개발/공급계약/지분투자/인수/업무협약/파트너십) 중 하나.', max_length=50),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='relation_org_a',
            field=models.ForeignKey(blank=True, help_text='관계 전용. 관계의 한쪽 기업.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='setting.organization'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='relation_org_b',
            field=models.ForeignKey(blank=True, help_text='관계 전용. 관계의 다른 쪽 기업.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='setting.organization'),
        ),
        migrations.AlterField(
            model_name='rundraft',
            name='content',
            field=models.TextField(help_text='Insight.content, Report.content 또는 OrgRelation.description.'),
        ),
        migrations.AlterField(
            model_name='rundraft',
            name='draft_type',
            field=models.CharField(choices=[('이슈', '이슈'), ('주간 보고서', '주간 보고서'), ('월간 보고서', '월간 보고서'), ('관계', '관계')], max_length=10),
        ),
    ]
