# Generated by Django 5.2 on 2026-09-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_news_duplicate_of'),
        ('setting', '0028_rundraft_created_relation_rundraft_relation_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundraft',
            name='content_keep',
            field=models.JSONField(blank=True, default=list, help_text='축약본 content_short 문장 번호.'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_change',
            field=models.CharField(blank=True, choices=[('new', '신규'), ('moved', '직전 순위에서 이동'), ('same', '유지')], default='', help_text='헤드라인 전용. 직전 지정과 견준 결과(5-2).', max_length=10),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_change_reason',
            field=models.TextField(blank=True, default='', help_text='헤드라인 전용. 교체 사유(5-2). 창 밖 이탈·중복 제외·다양성은 코드가, 그 밖의 재적용은 LLM이 채운다.'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_prev_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text="헤드라인 전용. headliner_change='moved'일 때만.", null=True),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text='헤드라인 전용. 1~3(2-4 상한 3).', null=True),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_sector',
            field=models.CharField(blank=True, default='', help_text='헤드라인 전용. 5-1 업권 라벨. Insight에 저장하지 않는다.', max_length=50),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_sector_unlisted',
            field=models.BooleanField(default=False, help_text='헤드라인 전용. 5-1 업권 목록에 없는 라벨이면 True.'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_source_draft',
            field=models.ForeignKey(blank=True, help_text='헤드라인 전용. 이번 배치 이슈 초안(RunDraft, TYPE_INSIGHT)이 후보면 그 pk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='setting.rundraft'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='headliner_source_insight',
            field=models.ForeignKey(blank=True, help_text='헤드라인 전용. 창 안 기존 확정 Insight가 후보면 그 pk(from_existing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.insight'),
        ),
        migrations.AddField(
            model_name='rundraft',
            name='implication_keep',
            field=models.JSONField(blank=True, default=list, help_text='이슈 전용. 축약본 implication_short 문장 번호.'),
        ),
        migrations.AddField(
            model_name='runjob',
            name='headliner_dropped',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='runjob',
            name='headliner_window_label',
            field=models.CharField(blank=True, default='', help_text='예: "창 7일 · 기준점 09.16 · 후보 1급 9건". job_key="insight"만 채운다.', max_length=200),
        ),
        migrations.AlterField(
            model_name='rundraft',
            name='content',
            field=models.TextField(help_text='Insight.content, Report.content, OrgRelation.description 또는(헤드라인 전용) 헤드라인 순위 사유(1-A 사슬 결과 한 문장).'),
        ),
        migrations.AlterField(
            model_name='rundraft',
            name='draft_type',
            field=models.CharField(choices=[('이슈', '이슈'), ('주간 보고서', '주간 보고서'), ('월간 보고서', '월간 보고서'), ('관계', '관계'), ('헤드라인', '헤드라인')], max_length=10),
        ),
    ]
