# Generated by Django 5.2 on 2026-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0029_rundraft_content_keep_rundraft_headliner_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='relation_conflict_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runjob',
            name='relation_skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
