# Generated by Django 5.2 on 2026-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0030_runjob_relation_conflict_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runjob',
            name='relation_target_count',
            field=models.IntegerField(default=0),
        ),
    ]
