# Generated by Django 5.2 on 2026-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_insight_insight_headliner_order_idx_and_more'),
        ('setting', '0031_runjob_relation_target_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='runproposal',
            index=models.Index(fields=['run_job', 'status'], name='runproposal_runjob_status_idx'),
        ),
    ]
