# Generated by Django 5.2 on 2026-09-02 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('filter_prompt', models.TextField(blank=True)),
                ('compose_prompt', models.TextField(blank=True)),
                ('slack_channel_name', models.CharField(blank=True, max_length=100)),
                ('slack_webhook_url', models.URLField(blank=True, max_length=2000)),
                ('send_hour', models.PositiveSmallIntegerField(default=8)),
                ('send_minute', models.PositiveSmallIntegerField(default=0)),
                ('send_frequency', models.CharField(choices=[('weekday', '평일 (월~금)'), ('daily', '매일')], default='weekday', max_length=10)),
                ('send_is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsroomKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('sort', models.CharField(choices=[('date', '최신순'), ('sim', '관련도순')], default='date', max_length=10)),
                ('display', models.PositiveSmallIntegerField(default=20)),
                ('newsroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='newsroom.newsroom')),
            ],
        ),
        migrations.CreateModel(
            name='NewsroomArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('filter_status', models.CharField(choices=[('pending', '판정 전'), ('passed', '통과'), ('rejected', '제외')], db_index=True, default='pending', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('newsroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsroom.newsroom')),
            ],
            options={
                'ordering': ['-published_at', '-pk'],
                'unique_together': {('newsroom', 'url_hash')},
            },
        ),
    ]
