# Generated by Django 5.2 on 2026-09-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroomarticle',
            name='judged_by',
            field=models.CharField(blank=True, choices=[('수동(RA)', '수동(RA)'), ('자동(LLM)', '자동(LLM)')], default=None, max_length=20, null=True),
        ),
    ]
