# Generated by Django 5.2 on 2026-09-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0005_newsroomarticle_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroomarticle',
            name='is_ai_related',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsroomarticle',
            name='source_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsroom.newsroomkeyword'),
        ),
    ]
