# Generated by Django 5.2 on 2026-09-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0007_seed_kyobo_affiliate_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsroomAffiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('newsroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to='newsroom.newsroom')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='newsroomarticle',
            name='affiliates',
            field=models.ManyToManyField(blank=True, related_name='articles', to='newsroom.newsroomaffiliate'),
        ),
    ]
