# Generated by Django 5.2 on 2026-09-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0009_seed_affiliates_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroomarticle',
            name='body_is_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
