# Generated by Django 5.2 on 2026-09-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0011_backfill_body_is_truncated'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroomarticle',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='같은 사건을 다루는 대표 기사. 대표 기사 자신은 None이다. filter_status는 두 기사 모두 passed로 그대로 둔다 — 이 필드로만 묶고 제외 처리하지 않는다. 대표만 펼쳐 보이고 나머지를 묶음으로 접어 보이는 것은 화면(PD) 몫이다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='newsroom.newsroomarticle'),
        ),
        migrations.AddField(
            model_name='newsroomarticle',
            name='impact_rank',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text="2단계 LLM이 매긴 비즈니스 파급력 순위(1이 가장 크다). 같은 실행 배치 안에서만 비교 가능하다 — 서로 다른 날 배치의 순위를 직접 비교하지 않는다. 3단계 발송문이 이 순서를 그대로 따른다 (정책 12-2 표 '2단계는 그 순서를 따름').", null=True),
        ),
    ]
