# Generated by Django 5.2 on 2026-09-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0012_newsroomarticle_duplicate_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsroomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '초안'), ('sent_manual', '수동 발송함'), ('sent_auto', '자동 발송함'), ('failed', '실패')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='messages', to='newsroom.newsroomarticle')),
                ('newsroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newsroom.newsroom')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
