# Generated by Django 5.2 on 2026-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0013_newsroommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroomarticle',
            name='judged_by',
            field=models.CharField(blank=True, choices=[('수동(RA)', '수동(RA)'), ('자동(LLM)', '자동(LLM)'), ('코드(제목 규칙)', '코드(제목 규칙)')], default=None, max_length=20, null=True),
        ),
    ]
