# Generated by Django 5.2 on 2026-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0014_alter_newsroomarticle_judged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroommessage',
            name='status',
            field=models.CharField(choices=[('draft', '초안'), ('sent_manual', '발송 표시'), ('sent_auto', '자동 발송함'), ('failed', '실패')], default='draft', max_length=15),
        ),
    ]
