# Generated by Django 5.2 on 2026-06-26 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generating', '생성중'), ('done', '완료'), ('failed', '실패')], default='generating', max_length=20)),
                ('slack_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-week'],
            },
        ),
        migrations.CreateModel(
            name='ReportNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'unique_together': {('report', 'news')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='news',
            field=models.ManyToManyField(related_name='reports', through='reports.ReportNews', to='news.news'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('year', 'week')},
        ),
    ]
