# Generated by Django 5.2 on 2026-06-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date_from']},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='report',
            name='week',
        ),
        migrations.RemoveField(
            model_name='report',
            name='year',
        ),
        migrations.AddField(
            model_name='report',
            name='period_type',
            field=models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간')], default='weekly', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('period_type', 'date_from')},
        ),
    ]
