# Generated by Django 5.2 on 2026-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content_short',
            field=models.TextField(blank=True),
        ),
    ]
